### ISSUE TITLE
Update de dispositivos no ocorrencia-server está criando um novo registro

### ISSUE THREAD

**Issue by dcruzb** [sdpos20191/mariadapenhabackend#2]
O update de dispositivos não está atualizando, retorna código 200 com o json correto, mas não atualizou, e na verdade ele adicionou um novo no update

**Comment by leandrooguit** [comment]
o atualização não existe mais no banckend.

**Comment by dcruzb** [comment]
A atualização de dispositivos ainda existe, e precisa existir.
Mas o bug foi corrigido e estou encerrando o issue
