### ISSUE TITLE
Update de ocorrencias está criando um novo registro

### ISSUE THREAD

**Issue by dcruzb** [sdpos20191/mariadapenhabackend#6]
O update de dispositivos não está atualizando, retorna código 200 com o json correto, mas não atualizou, e na verdade ele adicionou um novo no update

`PUT   /api/v1/ocorrencias/{id}  => Atualizar Ocorrencia`

**Comment by leandrooguit** [comment]
não existe mais o atualizar no banckend de ocorrências
