### ISSUE TITLE
Ajustes na arquitetura

### ISSUE THREAD

**Issue by dcruzb** [sdpos20191/mariadapenhabackend#8]
As entidades de dispositivos e das ocorrências não estão consistentes.
A ocorrência está gravando um novo dispositivo, e que não tem dependência da entidade de dispositivo.
Em ocorrência deveria ser gravado somente o id do dispositivo

**Comment by fagnerffcs** [comment]
Mudança do atributo de Ocorrencia para String (referencia do id do Dispositivo) ao inves de usar o proprio objeto Dispositivo.
